### ISSUE TITLE
Empty File in Data Lake Bucket

### ISSUE THREAD

**Issue by titan550** [HealthEngineAU/adobe-analytics-data-lake#1]
Thank you for publishing this work. I created the stack and loaded files to the S3 bucket as you had instructed but I see one and only one empty file (0 bytes) named "hit-data_$folder$" in the data lake bucket. Crawler does not find any tables and therefore I cannot query the data.

Can you please check the Python file load-data.py?

![image](https://user-images.githubusercontent.com/5111141/59134536-62c4a200-8930-11e9-83ee-70b880527c28.png)

**Comment by titan550** [comment]
I had selected more than the October 2016 columns. I selected October 2016 columns from the Adobe Analytics portal and it resolved the issue.

**Comment by chriskl** [comment]
So it's all working now?  You're probably the first person other than me to really try this solution.  Hopefully I didn't make any mistakes in it...

**Comment by titan550** [comment]
@chriskl  It's solid work. I was so happy when I found your repo. I just corrected a few typos that I will send over to you in a pull request.

Another question, what did you do about the lookup tables and resolving things like country codes? For example, country code 300 is U.S. commercial but in the output parquet files it is just 300. Do you suggest replacing the lookup codes with actual values in the final table?

**Comment by chriskl** [comment]
Hi John,

I never got around to processing the lookup data.  That would be an
exercise for the reader :)

There's an example of processing it here:

https://aws.amazon.com/blogs/big-data/closing-the-customer-journey-loop-with-amazon-redshift-at-equinox-fitness-clubs/

In that case it uses the metadata to get column names...but you can't get
types.

We could process the lookup files and substitute in new columns into the
parquet files perhaps, or just set up a new table each hour with the lookup
data.  Unfortunately the lookup data is a zipped set, which makes it even
harder to process. And I'm no gun Spark or Python coder :(

Here's a bounty I put on StackExchange:

https://stackoverflow.com/questions/55272228/how-to-prevent-processing-files-twice-with-spark-dataframes

Other references:

* https://github.com/awslabs/athena-adobe-datafeed-splitter
*
http://datafeedtoolbox.com/how-to-setup-a-data-lake-and-start-making-sql-queries-with-adobe-analytics-aws-s3-and-athena/

Good luck :) . Please submit cool stuff back :) . I might be doing one of
these for Braze soon too.

Chris
